AABB = [-0.7, -0.7, -0.7, 0.7, 0.7, 0.7]

NUM_RAYS = 20000

MLP_INPUT_SIZE = 3
MLP_ENCODING_SIZE = 24
MLP_INPUT_SIZE_AFTER_ENCODING = MLP_INPUT_SIZE * MLP_ENCODING_SIZE * 2
MLP_OUTPUT_SIZE = 4
MLP_HIDDEN_LAYERS = 3
MLP_UNITS = 64

TINY_CUDA_MIN_SIZE = 16

OCCUPANCY_GRID_RECONSTRUCTION_ITERATIONS = 20
OCCUPANCY_GRID_WARMUP_ITERATIONS = 5